### ISSUE TITLE
Retry once (or more?) on any TransportError

### ISSUE THREAD

**Issue by simonw** [simonw/google-drive-to-sqlite#18]
Got this exception:
```
  File "/Users/simon/Dropbox/Development/google-drive-to-sqlite/google_drive_to_sqlite/utils.py", line 79, in get
    response = httpx.get(url, params=params, headers=headers, timeout=self.timeout)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_api.py", line 189, in get
    return request(
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/Users/simon/.pyenv/versions/3.10.0/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.
```
Would be good to retry once if this happens.

**Comment by simonw** [comment]
https://www.python-httpx.org/exceptions/#the-exception-hierarchy shows the exception hierarchy:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/9599/154822684-1f28c10d-6a0c-4b76-9c8c-ff48dd06565a.png">

**Comment by simonw** [comment]
I want to retry on any form of `TransportError` i think - no point retrying a `DecodingError` or a `TooManyRedirects` error.

**Comment by simonw** [comment]
Sadly it looks like `httpx` itself has decided not to implement retry logic, so I need to build this myself:
- https://github.com/encode/httpx/issues/108

**Comment by simonw** [comment]
While testing this I'm going to want to see if any transport errors have occurred - I think I'll add a `-v/--verbose` flag to the `google-drive-to-sqlite files` command.

**Comment by simonw** [comment]
I'm only going to retry GET, I won't retry POST.

**Comment by simonw** [comment]
Now manually testing this by running:

    google-drive-to-sqlite files --folder 1E6Zg2X2bjjtPzVfX8YqdXZDCoB3AVA7i --nl --verbose > all-files.json-nl.txt

**Comment by simonw** [comment]
It's at `   37223 all-files.json-nl.txt` and 49MB now, 25 minutes after starting.

**Comment by simonw** [comment]
That actually worked! 162M file resulted, with no errors.

**Comment by simonw** [comment]
Now running this to see what happens:

     time google-drive-to-sqlite files all-files.db --import-nl all-files.json-nl.txt
    43.24s user 94.07s system 71% cpu 3:13.06 total

Produced a 80MB SQLite file, thanks presumably to the `owners` data being de-duplicated.

**Comment by simonw** [comment]
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/9599/154830042-79d811eb-a44d-4953-961d-1ed0b4ae2874.png">

I'm suspicious of the 14,100 rows in the `drive_users` table.

**Comment by simonw** [comment]
Confirmed, something went very wrong there:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/9599/154830053-ece80908-0da6-48c7-ae8d-e2c5afb299cc.png">

**Comment by simonw** [comment]
This is from a file created using:

    google-drive-to-sqlite files all-files.db --import-nl all-files.json-nl.txt

So hopefully I won't need to hit the API again while debugging this.

**Comment by simonw** [comment]
Added this debugging code:
```
diff --git a/google_drive_to_sqlite/utils.py b/google_drive_to_sqlite/utils.py
index 8c50278..26116b9 100644
--- a/google_drive_to_sqlite/utils.py
+++ b/google_drive_to_sqlite/utils.py
@@ -198,6 +198,8 @@ def save_files_and_folders(db, all):
         ):
             for file in sequence:
                 if file.get("lastModifyingUser"):
+                    lmu = file["lastModifyingUser"]
+                    assert lmu.get("permissionId")
                     file["lastModifyingUser"] = (
                         db["drive_users"]
                         .insert(
@@ -216,6 +218,7 @@ def save_files_and_folders(db, all):
                         for user in owners
                         if user["permissionId"] not in users_seen
                     ]
+                    assert not any(not u.get("permissionId") for u in missing_users)
                     if missing_users:
                         db["drive_users"].insert_all(
                             missing_users,
```
Ran it like this and found the bug:
```
% python -i $(which google-drive-to-sqlite) files all-files-2.db --import-nl all-files.json-nl.txt
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/bin/google-drive-to-sqlite", line 33, in <module>
    sys.exit(load_entry_point('google-drive-to-sqlite', 'console_scripts', 'google-drive-to-sqlite')())
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/google-drive-to-sqlite/google_drive_to_sqlite/cli.py", line 473, in files
    save_files_and_folders(db, all)
  File "/Users/simon/Dropbox/Development/google-drive-to-sqlite/google_drive_to_sqlite/utils.py", line 202, in save_files_and_folders
    assert lmu.get("permissionId")
AssertionError
>>> import pdb; pdb.pm()
> /Users/simon/Dropbox/Development/google-drive-to-sqlite/google_drive_to_sqlite/utils.py(202)save_files_and_folders()
-> assert lmu.get("permissionId")
(Pdb) lmu
{'kind': 'drive#user', 'displayName': '', 'me': False}
```

**Comment by simonw** [comment]
Sure enough that file has this:

     'lastModifyingUser': {'displayName': '', 'kind': 'drive#user', 'me': False},

I'm going to treat those as null.

**Comment by simonw** [comment]
Fixed that bug:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/9599/154830588-6ba5dd6d-08ad-4f7a-bdb3-885fb59867b4.png">
