### ISSUE TITLE
`drive_users` table fills up with null rows

### ISSUE THREAD

**Issue by simonw** [simonw/google-drive-to-sqlite#33]
Something went very wrong here:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/9599/154830053-ece80908-0da6-48c7-ae8d-e2c5afb299cc.png">

88 rows where permissionId is not null, 14,012 rows where permissionId is null.

_Originally posted by @simonw in https://github.com/simonw/google-drive-to-sqlite/issues/18#issuecomment-1046167012_

**Comment by simonw** [comment]
This is from a file created using:

    google-drive-to-sqlite files all-files.db --import-nl all-files.json-nl.txt

So hopefully I won't need to hit the API again while debugging this.

**Comment by simonw** [comment]
Added this debugging code:
```
diff --git a/google_drive_to_sqlite/utils.py b/google_drive_to_sqlite/utils.py
index 8c50278..26116b9 100644
--- a/google_drive_to_sqlite/utils.py
+++ b/google_drive_to_sqlite/utils.py
@@ -198,6 +198,8 @@ def save_files_and_folders(db, all):
         ):
             for file in sequence:
                 if file.get("lastModifyingUser"):
+                    lmu = file["lastModifyingUser"]
+                    assert lmu.get("permissionId")
                     file["lastModifyingUser"] = (
                         db["drive_users"]
                         .insert(
@@ -216,6 +218,7 @@ def save_files_and_folders(db, all):
                         for user in owners
                         if user["permissionId"] not in users_seen
                     ]
+                    assert not any(not u.get("permissionId") for u in missing_users)
                     if missing_users:
                         db["drive_users"].insert_all(
                             missing_users,
```
Ran it like this and found the bug:
```
% python -i $(which google-drive-to-sqlite) files all-files-2.db --import-nl all-files.json-nl.txt
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/bin/google-drive-to-sqlite", line 33, in <module>
    sys.exit(load_entry_point('google-drive-to-sqlite', 'console_scripts', 'google-drive-to-sqlite')())
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/google-drive-to-sqlite-Wr1nXkpK/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/google-drive-to-sqlite/google_drive_to_sqlite/cli.py", line 473, in files
    save_files_and_folders(db, all)
  File "/Users/simon/Dropbox/Development/google-drive-to-sqlite/google_drive_to_sqlite/utils.py", line 202, in save_files_and_folders
    assert lmu.get("permissionId")
AssertionError
>>> import pdb; pdb.pm()
> /Users/simon/Dropbox/Development/google-drive-to-sqlite/google_drive_to_sqlite/utils.py(202)save_files_and_folders()
-> assert lmu.get("permissionId")
(Pdb) lmu
{'kind': 'drive#user', 'displayName': '', 'me': False}
```

**Comment by simonw** [comment]
Sure enough that file has this:

     'lastModifyingUser': {'displayName': '', 'kind': 'drive#user', 'me': False},

I'm going to treat those as null.

**Comment by simonw** [comment]
That fixed it: 
<img width="532" alt="image" src="https://user-images.githubusercontent.com/9599/154830563-0dfe47f5-86e7-4fdc-9f28-734fa5fa9a08.png">
